### ISSUE TITLE
[CocoaPods issue] Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by kevinrenskers** [AgileBits/onepassword-app-extension#181]
I'm using 1PasswordExtension via CocoaPods. Version 1.1 works fine, but when I upgrade to 1.1.2 and try to compile my app, I get these errors:

```
Undefined symbols for architecture x86_64:
  "_AppExtensionErrorCodeCancelledByUser", referenced from:
      ___45-[RootViewController findLoginFrom1Password:]_block_invoke in RootViewController.o
  "_AppExtensionPasswordKey", referenced from:
      ___45-[RootViewController findLoginFrom1Password:]_block_invoke in RootViewController.o
  "_AppExtensionUsernameKey", referenced from:
      ___45-[RootViewController findLoginFrom1Password:]_block_invoke in RootViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Absolutely nothing else changed in my code.

**Comment by radazzouz** [comment]
Hi @kevinrenskers,

Thanks for taking the time to write to us :+1: 

Lately we've been getting a quite a few CocoaPods-related issues ( see #180 ). This leads me to believe that there might be a bug on their end.

By the looks of it, it seems that CocoaPods didn't pull version `1.1.2` properly. Did you try to clear Xcode's derived data and restart it?

Can you please force to update to version `1.1.2` in your `Podfile` the someway that I did in this [sample project](https://com-agilebits-users.s3.amazonaws.com/rad/ACME%20CocoaPods.zip)?

It would be great if you could replicate this issue in the sample project that I've sent you and send it back to me. This we we can determine what causes the issue.

Please let me know how this goes. 

If you are using CocoaPods `0.36.0.rc.1` please make sure that you check the interesting discussion in issue #180 

Cheers!

**Comment by kevinrenskers** [comment]
Hm weird, it works fine on another computer, so it probably can be solved by clearing derived data or something like that on the original computer. Will let you know.

**Comment by dmcgloin** [comment]
Same issue. Not using CocoaPods. Clearing derived data resolved issue.

**Comment by kevinrenskers** [comment]
Yea solved it on my other computer as well. Closing this.

**Comment by radazzouz** [comment]
Hi guys,

Thanks for letting us know that you've got it all sorted out :smile: 

Cheers!
